apiVersion: fridaycommit.io/v1alpha1
kind: GithubRepo
metadata:
  name: seb-demo-test-repo
spec:
  repoName: seb-demo-test-repo
  users:
    - username: "felixlut"
      permission: "maintain"
    - username: "ViktorLindgren95"
      permission: "admin"
