apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FridayCommit/seb-demo.git
    targetRevision: HEAD
    path: k8s/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # This doesn't actually do anything, since ArgoCD needs to exists before it can create any namespaces. Leaving this in to confom with the other applications (this could probably be an applicationset anyways)
  syncPolicy:
    syncOptions:
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FridayCommit/seb-demo.git
    targetRevision: HEAD
    path: k8s/crossplane-system
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: end-user
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FridayCommit/seb-demo.git
    targetRevision: HEAD
    path: k8s/end-user
  destination:
    server: https://kubernetes.default.svc
    namespace: end-user
  syncPolicy:
    syncOptions:
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
