apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml
- namespace.yaml
- application.yaml
patches:
- path: patches/argocd-config.yaml
