apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - provider-config.yaml
  - github-creds.yaml
  - composites
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
